### ISSUE TITLE
Add breadcrumbs

### ISSUE THREAD

**Issue by samheather** [samheather/iapt2group1#28]

**Comment by svetlanaangelova** [comment]
Do you think it will be a problem if a user goes to View project from their Dashboard but the breadcrumbs show "Home / View Project" instead of "Home / Dashboard / View Project/?

**Comment by j6mes** [comment]
This is a good idea Sve.

An easy fix for this sam would be to check if the user.auth_id == project.owner_id, then show a diff set of breadcrumbs.

On 3 Apr 2015, at 09:25, svetlanaangelova <notifications@github.com<mailto:notifications@github.com>> wrote:

Do you think it will be a problem if a user goes to View project from their Dashboard but the breadcrumbs show "Home / View Project" instead of "Home / Dashboard / View Project/?

**Comment by samheather** [comment]
It also doesn't work if the project is opened from the search page etc.

On Friday, 3 April 2015, j6mes notifications@github.com wrote:

> This is a good idea Sve.
> 
> An easy fix for this sam would be to check if the user.auth_id ==
> project.owner_id, then show a diff set of breadcrumbs.
> 
> On 3 Apr 2015, at 09:25, svetlanaangelova <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');><mailto:
> notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>>> wrote:
> 
> Do you think it will be a problem if a user goes to View project from
> their Dashboard but the breadcrumbs show "Home / View Project" instead of
> "Home / Dashboard / View Project/?
> 
> —
> Reply to this email directly or view it on GitHub<
> https://github.com/samheather/iapt2group1/issues/28#issuecomment-89217786>.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/samheather/iapt2group1/issues/28#issuecomment-89221668
> .

## 

_Sam Heather_ | pingWHEN | m: +44 7585 441757 <00447585441757> | e:
sam@heather.sh

Website: www.pingwhenapp.com
Facebook: www.facebook.com/pingwhen
https://www.facebook.com/pages/Pingwhen/292317570939511
*a personal safety app for when you arrive (or don't) to a location. *
