### ISSUE TITLE
Number of transcriptions is confusing

### ISSUE THREAD

**Issue by svetlanaangelova** [samheather/iapt2group1#56]
Rejected transcriptions are not counted in on the summary.

**Comment by samheather** [comment]
Linked to #68

**Comment by svetlanaangelova** [comment]
@samheather @j6mes , is there any reason why we're counting only non-rejected transcriptions? I find it weird to see on the dashboard a count of 1 for example when that one transcription has been accepted.

**Comment by samheather** [comment]
I think we should two numbers. Something like:

3 pending transcriptions
11 total transcriptions

(where total includes rejected, accepted, and not-yet-rejected-or-accepted)

(if the column header were to be renamed to 'transcriptions' instead of status, this could be shortened to:
3 pending
11 total
)

**Comment by samheather** [comment]
lgtm, approval :) Great job Sve!
